### ISSUE TITLE
No module named 'Image'

### ISSUE THREAD

**Issue by dkim777** [hamedtaha/Cryptocurrency-exchange-raspberrypi#1]
I keep getting this error even though I have installed Image(pillow) library.
any ideas?

```
pi@raspberrypi:~/exchange/Cryptocurrency-exchange-raspberrypi/raspberrypi/python $ sudo pip install pillow
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pillow in /usr/lib/python2.7/dist-packages (5.4.1)
pi@raspberrypi:~/exchange/Cryptocurrency-exchange-raspberrypi/raspberrypi/python $ sudo python3 main.py
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    import epd2in7b
  File "/home/pi/exchange/Cryptocurrency-exchange-raspberrypi/raspberrypi/python/epd2in7b.py", line 28, in <module>
    import Image
ModuleNotFoundError: No module named 'Image'
```

**Comment by dkim777** [comment]
I fixed it by changing the line to following

from PIL import Image

but now I'm getting this error.

```
thon $ sudo python3 main.py
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    main()
  File "main.py", line 41, in main
    frame_black = [0] * (epd.width * epd.height / 8)
TypeError: can't multiply sequence by non-int of type 'float' 
```
